spring.application.name=templates

# Server Configuration
server.servlet.context-path=/api/${spring.application.name}

# Spring Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,env,beans,configprops
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoints.web.path-mapping.health=health
management.endpoints.web.path-mapping.info=info
management.endpoints.web.path-mapping.metrics=metrics

# OpenAPI Documentation Configuration
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/documentation
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha